config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'uploads' => 'file_upload#show', as: :show_uploads
  get 'new_upload' => 'file_upload#new', as: :new_upload
  post 'upload' => 'file_upload#create', as: :upload

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/file_upload_controller.rb
require 'file_manager'

class FileUploadController < ApplicationController
	def show
		@image_paths = FileManager.get_imagepaths("public/files/")
	end

  def new
  end

  def create
  	file = params[:file]
  	filename = FileManager.upload_file(file)

  	redirect_to show_uploads_url
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_upload_helper.rb
module FileUploadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_upload/new.html.erb
<h1>File upload example</h1>

<%= form_tag(upload_path, :method => "post", :enforce_utf8 => false, :multipart => true) do %>
	<%= file_field_tag 'file' %>

	<%= submit_tag "Upload" %>
<% end %>

app/views/file_upload/show.html.erb
<h1>All files in /files folder</h1>

<% unless @image_paths.empty? %>
	<div class="images">
		<% @image_paths.each do | path | %>
			<img width="400" height="400" src="/files/<%= path %>">
		<% end %>
	</div>
<% else %>
	<div>
		<p>There are no images in stored this folder</p>
	</div>
<% end %>

<%= link_to 'Upload image', new_upload_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HolderRepo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>